#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='chrome'
fi

#
# Editors
#
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'
export TERM='screen-256color'
export KEYTIMEOUT=1
export PANEL_FIFO="/tmp/panel-fifo"
export GTAGSLABEL=pygments




# List of accounts to read the last tweet from, comma separated
# The first in the list is read by the party parrot.
export TTC_BOTS='tinycarebot,selfcare_bot,magicrealismbot'

# List of folders to look into for `git` commits, comma separated.
export TTC_REPOS='~'

# Location/zip code to check the weather for. Both 90210 and "San Francisco, CA"
# _should_ be ok (the zip code doesn't always work -- use a location
# first, if you can). It's using weather.service.msn.com behind the curtains.
export TTC_WEATHER='Bordeaux'

# Set to false if you're an imperial savage. <3
export TTC_CELSIUS=true

# Unset this if you _don't_ want to use Twitter keys and want to
# use web scraping instead.
export TTC_APIKEYS=true

# Refresh the dashboard every 20 minutes.
export TTC_UPDATE_INTERVAL=20
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/cuda/lib64"
export CUDA_HOME=/opt/cuda/
# Twitter api keys
export TTC_CONSUMER_KEY='RphnFwbxWZ2S0v58nVAAAjlB1'
export TTC_CONSUMER_SECRET='h8wh5g7YornpO1Q5a47TZDuvv6hqObsaZY0Pe9kbysh5plTrWt'
export TTC_ACCESS_TOKEN='856524279764144128-q7R6glvdd8W2fr4R0vcErIaA1XPSmNy'
export TTC_ACCESS_TOKEN_SECRET='fHBhTsM1SgCfyna5XYuJ0w0U9T5ReiSrqOAz8CgggZg2U'

# Note: in tiny-terminal-care < 1.0.7, the recommended variables for the Twitter
# API keys were the ones before. As of 1.0.8, they are deprecated
# (because the names are too generic), but will still be supported
# until the next major version.
export CONSUMER_KEY='RphnFwbxWZ2S0v58nVAAAjlB1'
export CONSUMER_SECRET='h8wh5g7YornpO1Q5a47TZDuvv6hqObsaZY0Pe9kbysh5plTrWt'
export ACCESS_TOKEN='856524279764144128-q7R6glvdd8W2fr4R0vcErIaA1XPSmNy'
export ACCESS_TOKEN_SECRET='fHBhTsM1SgCfyna5XYuJ0w0U9T5ReiSrqOAz8CgggZg2U'






#
#rt KEYTIMEOUT=1
# Language
#

#if [[ -z "$LANG" ]]; then
  #export LANG='en_GB.UTF-8'
#fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
 "/opt/java/bin:/usr/share/perl5/vendor_perl/auto/share/dist/Cope:/usr/local/bin:/usr/local/sbin:/home/will/.local/bin"
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="$(mktemp -d)"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi
#[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
#if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
#  exec startx
#fi
